language: clojure

jdk:
- openjdk8

services:
  - docker

sudo: required

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: jVcJHN640iufSBGSmAoeMNk54tNmnQkXgvRNeDNGfVtUY/+TPKGyMNCrv5YssSQPBI3rljb1Ct8lsYwVw4Rh/dahGrZ0+w6lsPaQhX3KdhKGKbbmEn54ozOUAnBE6XcyLi/gZJlU2V9rOtOxi8R6PcKWttcbxUCYHdBXeWf3MvaVSVu8Aqx2mlg9+FPVty05evIuaMnA3HBb+1IpgKJ2yXwIn6fJuDJ6q913k4x9+lqruQRxyWs5CGpNYRsWiXaql5flliKfkLBzQWMojD+b/SAPByBVrP9myrpxMMltYHBMRS+1fMPDOirLWkH0ecQw7EvZtThMJrx28r72vj+SUQ8i9nfTazmMWQHHgUInJZ6zpUT8fL529K6XZcV6BqkU1d/1KfnaarKfxxoEHY0DzfrhF2Zmwq7lfnw006KR9LI3NCGolnJvira0wZcPduwTVaXyJiDvl1hIytGglm0ajuA9VllpusPT6IYrhsuGSGAoWkuoMOJvP1t3SBXA3bDdpIvAp3q9Ivf+ies6aHqCwmBByvCyvGg/j8TpNdYg398sMAHpRcDGB/dGB6Nnzg7Zbboe9WpcaXT0ASVuToRQkfSxe3lQLhwuDkwtlhKdyiF4zm5MhRXl7vT/Ik+gW3DYxy5P6VcPnVzrp9V0z9SmuxrKg/0Hkkc8BzblXZ5tXQE= # DOCKER_USER
  - secure: zjn2GGtl9r0QpgG78xSBIHEFJ8Si2DEhMa01rFvi1uGJ9Vk7mdvzHPAbk1lVyNME2TTHHGEFH/62Fzvy5lLgklM6rHAvbu4PUB6PRW4xhd+iRdEICDkWAyw7rLAs3u8Pu7VA+7OgnH6BU6AHAg66Q5EK1QTGBqOIUuDpWxDsnWTLHNWG8OLAYzNObYsuvHHYssR6IKkUH+TNZM29govmNoCN68aPv12BTwXo4/FJWf9Of4f/xauFcbxoKm8zQek+1oVsTxfgj3mLvmL0MXcJIBndaXf0jFg7cU3JKJE7CirEsFUr9LrhkCVi5qPYoKNqpi2r7go65IGnCwKTNnFTiUTZt/pqCEjdDfPxwgQjXds+ac36SGGhh8EmdB5vyYS3XLdSorCfmURxMSdJeZgpqipNaFDqYQky7maFs/U8StygnWfQQQVpLz3haCcyUtTtQ9rAVQpPwuvOdCLDh8s73pb5enfa8UtBaP8ahspsntgsUvvkC9N38Ibi5g3cTQcxh7yEVYZoDZgyVL+axVS5rj6B7o3u3wXhpxinBEvepZGazjeVMy8aHmsEbD6E3XdLPSzUy+tM0ajs9OMtvwRRro3C5vbn3fjsVPBAYTGrHfDjqjDzqEBrWOjwoNuLV3jNkDGjVzX02Q85p5HGboTr2gjpQvvB8PI0xopKEuywVNA= # DOCKER_PASS

before_install:
  # - cd test/resources
  # vm.max_map_count=262144 is needed so elasticsearch 5 will start.
  # Defaults are too low.
  - sudo sysctl -w vm.max_map_count=262144
  #- docker-compose up -d
  - make docker-deps-up
  # - cd ../..
  - sudo apt-get update -qq

after_success:
  - bin/deploy
  - make docker-deps-down

notifications:
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
