language: clojure

jdk:
- openjdk8

services:
  - docker

sudo: required

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: jVcJHN640iufSBGSmAoeMNk54tNmnQkXgvRNeDNGfVtUY/+TPKGyMNCrv5YssSQPBI3rljb1Ct8lsYwVw4Rh/dahGrZ0+w6lsPaQhX3KdhKGKbbmEn54ozOUAnBE6XcyLi/gZJlU2V9rOtOxi8R6PcKWttcbxUCYHdBXeWf3MvaVSVu8Aqx2mlg9+FPVty05evIuaMnA3HBb+1IpgKJ2yXwIn6fJuDJ6q913k4x9+lqruQRxyWs5CGpNYRsWiXaql5flliKfkLBzQWMojD+b/SAPByBVrP9myrpxMMltYHBMRS+1fMPDOirLWkH0ecQw7EvZtThMJrx28r72vj+SUQ8i9nfTazmMWQHHgUInJZ6zpUT8fL529K6XZcV6BqkU1d/1KfnaarKfxxoEHY0DzfrhF2Zmwq7lfnw006KR9LI3NCGolnJvira0wZcPduwTVaXyJiDvl1hIytGglm0ajuA9VllpusPT6IYrhsuGSGAoWkuoMOJvP1t3SBXA3bDdpIvAp3q9Ivf+ies6aHqCwmBByvCyvGg/j8TpNdYg398sMAHpRcDGB/dGB6Nnzg7Zbboe9WpcaXT0ASVuToRQkfSxe3lQLhwuDkwtlhKdyiF4zm5MhRXl7vT/Ik+gW3DYxy5P6VcPnVzrp9V0z9SmuxrKg/0Hkkc8BzblXZ5tXQE= # DOCKER_USER
  - secure: NYRVBz6Z3No1eicuXP7QIcWgcSi7FjMvx//4lr51znOryD2JV0A+vEDekPbW19/B5G+py6OrRbuOjdBNkECdo4MneaWwZJu9auXPZWnMqdntUlRmm5bice9vjQP9OhoxFOuF6uKszLAs+O7HDixgrH/0dYy8u6Va+KeMynVX0OxT5OdRkWZvDtCfXFu9XI0+mfpW7Mrq3BSrZ4QoWqSNrka8W4QtpgrNL/3vXwqwNcEOHOym9SBiZwYOoXlnedXh0Y5JDTLNOTLYQqCpD7f+H0D6/4NCxe1MvK8pr7M8ENj+wTzmrOs0JEu4Mc8x2MrvMtb/eGw79XbwUywD4XvJsuAaLzbZengL8s30jRJivQjNMG7C/I6HOVK4ChHY7gxJ/L5V0P4f5OsbZ6GDCRU+EURGomTNsIxvCC6+6pwpdi6IvP8xk7H1foZoroA/qq1sxjnl9mRgLvaVT/2CM9pKRXonribyr/sWanjuSf4M+fJmhM2JjK7fC4u/EPEeHwTNTsv8GlnxYy7up6E0lqUasfldSSTlMtU6oCoVSmU8BXsbXZeIxXg827ocHxcbLqDl/dFaAJ68TcJ+ACQxa81rrDAynLgdmw1fLjF+leHlRO2XZaA8uZD4AhGMPpS5x/usYbtHisML8D23qE1EWlpdbEHgJhSU02CdA4GmMsJLiNY= # DOCKER_PASS

before_install:
  # - cd test/resources
  # vm.max_map_count=262144 is needed so elasticsearch 5 will start.
  # Defaults are too low.
  - sudo sysctl -w vm.max_map_count=262144
  #- docker-compose up -d
  - make docker-test-up
  # - cd ../..
  - sudo apt-get update -qq

after_success:
  - bin/deploy
  - make docker-test-down

notifications:
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
