language: clojure

jdk:
- openjdk8

services:
  - docker

sudo: required

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "whrEKmFruqHmsSAaL8FJwj1iGIIzQpzRN5/AchGdypAmjSSP0iCyhV46AkJRllf7tomUMEaqb1AtAN+Ve2xXk2Z5rjM8cCiHsGarFfGhp4oLzI4xf/qGrUiDY9Vge929Rz0gwq/jlY7moXLe8SKS1gzayC78C1T53fNNwbbQefOR4t7DMCYDuUed4ZucGLcOsR8SJVm+5Xu87RnhcNiQE5fj6XGeyEhiZu6D7J2qtXJkaYyV6vKMEgPC5ypqqEjiW5pJcq6EW3MvoNI3XTqqyxx44H47DIS2PIysTC+NLdL9+TMWURztW3OCMBwaCbzpkyA3KOBX7WnrWVuBstMHb0EMLfVIq72kqYaj2+gzHjVwWCYosjc0XSpw5XVMb3ssru6Xwp2P9Z0kqlQGs77m9UbN9aiKkH3Zq6sIHFMimsa7L0bL1q5lS8ef6ywBmtnxvlvWVQ8mOT7fBfSuScva7ahahv/EjwAXQBek9mhYlySmeYcBMoIqVdk/EQZ/CW8iyAbvXq1KuR5V28QsAyLhzPvXzPnyoa/Mbk59q1hGc5tgtIWUAtZ3tynvZD6mk3PjaRTkQwRt1BdqkK3LfotuQYQfn/QM0TqBwnAHQY87UkapqLvaDwRt08i7ROIbNOoLx8zHHeT3zR3Jb6us+nMAc4YQnMgnaUYad48Ek4C+Rw0=" # DOCKER_USER
  - secure: "JR89n0IhTgsI11WgQ3DIHDJS18WyIvVE6E2x6eXhfgxJZP82rPuVgF5GJvbIzZsiiwiNJB3OYqK2OBTX6/8jxkY2VBnUcVUNpkqCgQCsLEJsMbOhGAo8gcHnNfo3gpG9dqYLba2YX7JUx/XcOMSl7Pd7hbRZOJPpQPP7guOuPf8cx9iUqhJwtsrQDOv29SrECoLG/04NeJ79VhNszdjjuT2UFU0bVH3NB9mIQ8NAoZ1ZA4dD56lmiExO4/24XNN5bWTNYnGdS2AzDFSO3c6f0iI1ICycbWNWPHvWFcdtNEexLJhAovyl1TVi8MdS3lf51BmcJx9EJPzpXE/xxRujHn56m/3wJUt74NTw33CpQRwqGfPiusX8vr/9HWVv1Xf9nwNL5ZdgJx2uivT/GmvCli7q3yWpSL7AWLvAaM1dysuGnVvtcDaR5XxTt771qmipzpyoaKFdAh80WB/9swhBPX+3a9p1BabFw0ccbmjFZL4uyz59bALafWZfsWzW4MxNr9+gmuWKQ2ecfzpHrfoB6ma/fIP8G/C0ibpOc+xAskO37lX1itcSAX3DTYVFfWK/zatVxUvO53I8PwyfyxMy/f4imL1+Dkwy31XG2K7htSZ2xrDEHyb+q+ASx3vF7BC0WVPWrFwETRZev7cdmsRUjGdADg1Xv2n3pqSSWBgpnmg=" # DOCKER_PASS

before_install:
  # - cd test/resources
  # vm.max_map_count=262144 is needed so elasticsearch 5 will start.
  # Defaults are too low.
  - sudo sysctl -w vm.max_map_count=262144
  #- docker-compose up -d
  - make docker-test-up
  # - cd ../..
  - sudo apt-get update -qq

after_success:
  - bin/deploy
  - make docker-test-down

notifications:
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
