version: '2'
services:

  elastic:
    image: elasticsearch:5.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"

  cassandra:
    image: cassandra:3.9
    ports:
      - "9042:9042"
    ulimits:
      memlock:
        soft: 68719476736
        hard: 68719476736
      as:
        soft: 68719476736
        hard: 68719476736
      nproc: 65535
      nofile:
        soft: 50000
        hard: 100000

#  landsat:
#    image: usgseros/lcmap-landsat:0.1.0-SNAPSHOT
#    command: >
#              {:database  {:contact-points \"cassandra\"
#                           :default-keyspace \"lcmap_landsat_dev\"}
#               :event     {:host \"rabbit\" :port 5672}
#               :http      {:port 5678 :join? false :daemon? true}
#               :server    {:exchange \"dev.lcmap.landsat.server\"
#                           :queue \"dev.lcmap.landsat.server\"}
#               :worker    {:exchange {:name \"dev.lcmap.landsat.worker\"}
#               :queue     {:name \"dev.lcmap.landsat.worker\"
#                           :bind [[\"dev.lcmap.landsat.server\" \"ingest\"]]}}
#               :search    {:url \"http://elastic:9200\"
#                           :ubid-index \"lcmap_landsat_dev_ubids\"
#                           :ubid-index-type \"ubid\"
#                           :max-result-size 10000}}
#    ports:
#      - "5678:5678"
#
#    depends_on:
#      - cassandra
#      - rabbit
#      - elastic
#    links:
#      - cassandra
#      - rabbit
#      - elastic
#    restart: on-failure
